# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='Photo',
            field=models.ImageField(default=0, max_length=50, upload_to='MediaAdministrator'),
        ),
    ]
