# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20170718_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='Photo2',
            field=models.ImageField(default=0, max_length=50, upload_to='MediaAdministrator2'),
        ),
    ]
