# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='ReleaseData',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
