# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_work_releasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Photo', models.ImageField(default=0, max_length=50, upload_to='MediaAdministrator')),
            ],
        ),
    ]
